version: '3'

services:
  mysql:
    image: my_mysql:latest
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  redis:
    image: my_redis:latest
    volumes:
      - ./redis:/usr/local/redis
    ports:
      - "6379:6379"

  php72:
    image: php72:latest
    ports:
      - "9000:9000"
    volumes:
      - ../:/data
      - ./php72/etc/php/php.ini:/usr/local/etc/php/php.ini
      - ./php72/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php72/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - redis
      - mysql
    privileged: true

  nginx:
    image: my_nginx:latest
    volumes:
      - ../:/data
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/vhost:/etc/nginx/conf.d
    links:
      - php72
    privileged: true
    ports:
      - "80:80"
